#!/bin/bash

echo "
deb http://deb.debian.org/debian trixie main contrib non-free
deb http://deb.debian.org/debian-security/ trixie-security main contrib non-free
deb http://deb.debian.org/debian trixie-updates main contrib non-free
" > /etc/apt/sources.list
dpkg --add-architecture armhf
# Update package manager
apt update
apt upgrade -y
# Install dependencies
apt install -y libc6:armhf gpg libasound-dev:armhf systemd:armhf libpulse-dev:armhf libgnutls*:arm64 libgnutls*:armhf zenity libopenvr-dev:armhf wget git  mesa-utils:arm64 xz-utils pulseaudio vk* vulkan-tools

# Clone Box86 repository
wget https://ryanfortner.github.io/box86-debs/box86.list -O /etc/apt/sources.list.d/box86.list 
wget -qO- https://ryanfortner.github.io/box86-debs/KEY.gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/box86-debs-archive-keyring.gpg 
apt update
apt install box86-android:armhf 
clear
# Clone Box64 repository
wget https://ryanfortner.github.io/box64-debs/box64.list -O /etc/apt/sources.list.d/box64.list 
wget -qO- https://ryanfortner.github.io/box64-debs/KEY.gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/box64-debs-archive-keyring.gpg 
apt update 
apt install box64-android -y
clear
