#!/bin/bash
clear
termux-setup-storage
pkg update -y
apt update -y
pkg install wget -y
apt -f install -y
pkg install openssl nano pulseaudio -y
termux-setup-storage
termux-change-repo
pkg upgrade -y
wget https://github.com/mebabo1/menano/releases/download/Box/bin.tar.gz  >/dev/null 2>&1
tar xf bin.tar.gz
rm -rf bin.tar.gz
cd /data/data/com.termux/files
echo "pkg download05"
wget -O box64.tar.xz https://github.com/mebabo1/menano/releases/download/Box/box64.tar.xz 2>&1 | pv -l > download.log
echo "pkg download04"
wget https://github.com/mebabo1/menano/releases/download/Box/caja.tar.gz >/dev/null 2>&1
echo "pkg download03"
wget https://github.com/mebabo1/menano/releases/download/Box/cajaf.tar.gz >/dev/null 2>&1
echo "pkg download02"
wget https://github.com/mebabo1/menano/releases/download/Box/cajarun.tar.gz >/dev/null 2>&1
echo "pkg download01"
wget https://github.com/mebabo1/menano/releases/download/Box/openbox_menu.tar.gz >/dev/null 2>&1
echo "pkg download00"
wget https://github.com/mebabo1/menano/releases/download/Box/SmartBox64.tar.gz >/dev/null 2>&1
wget https://github.com/mebabo1/menano/releases/download/Box/xfce4_settings.tar.gz >/dev/null 2>&1
wget https://github.com/mebabo1/menano/releases/download/Box/termux_vk.tar.xz >/dev/null 2>&1
echo "pkg tar xf"
rm -rf home/.local
tar xf box64.tar.xz
tar xf caja.tar.gz
tar xf cajaf.tar.gz
tar xf cajarun.tar.gz
tar xf openbox_menu.tar.gz
tar xf termux_vk.tar.xz
tar xf xfce4_settings.tar.gz
rm -rf openbox_menu.tar.gz box64.tar.xz caja.tar.gz cajaf.tar.gz termux_vk.tar.xz cajarun.tar.gz xfce4_settings.tar.gz
rm -rf /sdcard/Box64Droid01
rm -rf /sdcard/SmartBox64
tar xf SmartBox64.tar.gz
cp -r SmartBox64 /sdcard
rm -rf SmartBox64.tar.gz SmartBox64
echo "pkg download01"
wget -O glibc.tar.xz https://github.com/mebabo1/menano/releases/download/Box/glibc.tar.xz 2>&1 | pv -l > download.log
echo "pkg download00"
wget https://github.com/mebabo1/menano/releases/download/Box/alsa.tar >/dev/null 2>&1
echo "pkg tar xf"
tar xf glibc.tar.xz
tar xf alsa.tar
rm -rf alsa.tar glibc.tar.xz
cd
echo "SmartBox64 can be operated using x11 commands"
rm -rf install
