#!/bin/bash

termux-setup-storage

pkg install termux-am x11-repo -y
pkg install xorg-xrandr -y
pkg install termux-x11-nightly -y
pkg install feh -y
pkg ins tint2 -y
pkg install picom -y
pkg install xfce4-taskmanager -y
pkg install caja -y
pkg install openbox -y
cd /data/data/com.termux/files
rm -rf opt
wget https://github.com/mebabo1/menano/releases/download/Box/box64.tar.xz
tar xf box64.tar.xz
rm -rf box64.tar.xz
wget https://github.com/mebabo1/menano/releases/download/Box/python.tar.gz
tar xf python.tar.gz
rm -rf python.tar.gz
wget https://github.com/mebabo1/menano/releases/download/Box/termux_vulkan.tar.gz
tar xf termux_vulkan.tar.gz
rm -rf termux_vulkan.tar.gz
wget https://github.com/mebabo1/menano/releases/download/Box/caja.tar.gz
tar xf caja.tar.gz
rm -rf caja.tar.gz
wget https://github.com/mebabo1/menano/releases/download/Box/openbox_menu.tar.gz
tar xf openbox_menu.tar.gz
rm -rf openbox_menu.tar.gz
cd /sdcard/
wget https://github.com/mebabo1/menano/releases/download/Box/Box64Droid01.tar.gz
tar xf Box64Droid01.tar.gz
rm -rf Box64Droid01.tar.gz
cd
echo "run x11 and x44"
rm -rf install03
