#!/bin/bash

termux-setup-storage

pkg install termux-am x11-repo -y
pkg install xorg-xrandr xwayland -y
pkg install termux-x11-nightly feh tint2 picom xfce4-taskmanager caja pv -y
pkg install openbox -y
wget https://github.com/mebabo1/menano/releases/download/Box/bin.tar.gz  >/dev/null 2>&1
tar xf bin.tar.gz
rm -rf bin.tar.gz
cd /data/data/com.termux/files
rm -rf opt
echo "pkg download06"
wget -O box64.tar.xz https://github.com/mebabo1/menano/releases/download/Box/box64.tar.xz 2>&1 | pv -l > download.log
echo "pkg download05"
wget -O python.tar.gz https://github.com/mebabo1/menano/releases/download/Box/python.tar.gz 2>&1 | pv -l > download.log
echo "pkg download04"
wget https://github.com/mebabo1/menano/releases/download/Box/caja.tar.gz >/dev/null 2>&1
echo "pkg download03"
wget https://github.com/mebabo1/menano/releases/download/Box/cajaf.tar.gz >/dev/null 2>&1
echo "pkg download02"
wget https://github.com/mebabo1/menano/releases/download/Box/cajarun.tar.gz >/dev/null 2>&1
echo "pkg download01"
wget https://github.com/mebabo1/menano/releases/download/Box/openbox_menu.tar.gz >/dev/null 2>&1
echo "pkg download00"
wget https://github.com/mebabo1/menano/releases/download/Box/SmartBox64.tar.gz >/dev/null 2>&1
echo "pkg tar xf"
tar xf box64.tar.xz
tar xf python.tar.gz
tar xf caja.tar.gz
tar xf cajaf.tar.gz
tar xf cajarun.tar.gz
tar xf openbox_menu.tar.gz
rm -rf openbox_menu.tar.gz box64.tar.xz python.tar.gz caja.tar.gz cajaf.tar.gz cajarun.tar.gz
rm -rf /sdcard/Box64Droid01
rm -rf /sdcard/SmartBox64
tar xf SmartBox64.tar.gz
mv SmartBox64 /sdcard
rm -rf SmartBox64.tar.gz
cd
echo "run x11"
rm -rf install03
