#!/bin/bash
clear
termux-setup-storage
echo "pkg update."
pkg update -y
echo "install x11-repo."
pkg install wget -y &>/dev/null
wget https://github.com/mebabo1/menano/blob/File/termux-x11-1.02.07-0-all.deb
pkg install x11-repo && pkg install xorg-server-xvfb -y && dpkg -i ./*.deb
apt -f install -y &>/dev/null
echo "pkg install nano pulseaudio."
pkg install nano pulseaudio -y &>/dev/null
rm -rf termux-x11-1.02.07-0-all.deb install termux-x11-1.02.07-0-any.pkg.tar.xz output-metadata.json
pkg install proot-distro -y &>/dev/null
