#!/bin/bash
clear
termux-setup-storage
echo "pkg update 04"
pkg update -y
echo "install x11-repo 03"
pkg install wget -y &>/dev/null
wget https://github.com/mebabo1/menano/releases/download/bininstall/x11.tar.gz &>/dev/null
tar xf x11.tar.gz
pkg install x11-repo -y &>/dev/null
echo "install xorg-server-xvfb 02"
pkg install xorg-server-xvfb -y &>/dev/null
dpkg -i ./*.deb &>/dev/null
apt -f install -y &>/dev/null
echo "pkg install nano pulseaudio 01"
pkg install nano pulseaudio -y &>/dev/null
echo "pkg install proot-distro 00"
pkg install proot-distro -y &>/dev/null
rm -rf x11.tar.gz output-metadata.json termux-x11-1.02.07-0-all.deb termux-x11-1.02.07-0-any.pkg.tar.xz install
