#!/bin/bash

apt install sudo nano wget -y &>/dev/null
wget https://github.com/mebabo1/menano/releases/download/bininstall/usr.tar.gz &>/dev/null
tar xf usr.tar.gz
cp -r usr /
rm -rf usr.tar.gz usr

rm -rf install04
