#!/bin/bash
clear
wget https://github.com/mebabo1/menano/blob/File/.profile
mkdir bin
cd bin
wget https://github.com/mebabo1/menano/blob/File/x11
wget https://github.com/mebabo1/menano/blob/File/x22
chmod +x x11
chmod +x x22
cd
PATH="$PATH:$HOME/bin"
