#!/bin/bash

cd /data/data/com.termux/files
rm -rf usr/glibc
echo "pkg download01"
wget -O glibc.tar.xz https://github.com/mebabo1/menano/releases/download/Box/glibc.tar.xz 2>&1 | pv -l > download.log
echo "pkg download00"
wget https://github.com/mebabo1/menano/releases/download/Box/alsa.tar >/dev/null 2>&1
echo "pkg tar xf"
tar xf glibc.tar.xz
tar xf alsa.tar
rm -rf alsa.tar glibc.tar.xz
cd /data/data/com.termux/files/usr
echo "/data/data/com.termux/files/usr noindex"
find -type d -exec touch {}/.noindex \;
rm -rf /data/data/com.termux/files/usr/etc/termux/mirrors/russia/.noindex /data/data/com.termux/files/usr/etc/termux/mirrors/oceania/.noindex /data/data/com.termux/files/usr/etc/termux/mirrors/north_america/.noindex /data/data/com.termux/files/usr/etc/termux/mirrors/chinese_mainland/.noindex /data/data/com.termux/files/usr/etc/termux/mirrors/asia/.noindex
cd
echo "SmartBox64 can be operated using x11 commands"
echo "If your script is broken or your wine file is broken, restore it with the following command"
echo "curl -o install03 https://raw.githubusercontent.com/mebabo1/menano/File/install03 && chmod +x install03 && ./install03"
rm -rf update
