#!/bin/bash
clear
rm -rf ubuntu22-fs start-ubuntu22.sh ubuntu22.sh ubuntu22-binds
pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu22/ubuntu22.sh -O ubuntu22.sh && chmod +x ubuntu22.sh
clear
rm -rf bin
wget https://github.com/mebabo1/menano/releases/download/virgl/bin.tar.gz
tar xf bin.tar.gz
rm -rf bin.tar.gz
bash ubuntu22.sh
