#!/bin/bash
clear
rm -rf ubuntu22-fs start-ubuntu22.sh ubuntu22.sh ubuntu22-binds
pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu22/ubuntu22.sh -O ubuntu22.sh && chmod +x ubuntu22.sh
clear
rm -rf bin
wget https://github.com/mebabo1/menano/releases/download/virgl/bin.tar.gz
tar xf bin.tar.gz
rm -rf bin.tar.gz
wget https://raw.githubusercontent.com/mebabo1/menano/File/x33
chmod +x x33
cp -r x33 bin
rm -rf x33
wget https://github.com/mebabo1/menano/releases/download/virgl/angle-virgl.tar.gz
tar xf angle-virgl.tar.gz
dpkg -i storage/shared/Download/angle-virgl/angle-android*.deb
dpkg -i storage/shared/Download/angle-virgl/virglrenderer-android*.deb
rm -rf angle-virgl.tar.gz angle-android_2.1.21474-75e64719-0_aarch64.deb virglrenderer-android_0.10.4-3_aarch64.deb built_termux-x11_packages.txt
bash ubuntu22.sh
