#!/bin/bash


cd /data/data/com.termux/files
rm -rf opt/wine
wget https://github.com/mebabo1/menano/releases/download/Box/wine9_9.tar.xz
wget https://github.com/mebabo1/menano/releases/download/Box/Scripts.tar.gz
tar xf wine9_9.tar.xz
tar xf Scripts.tar.gz
rm -rf wine9_9.tar.xz Scripts.tar.gz
cd
rm -rf wine9_9
