#!/bin/bash

cd /data/data/com.termux/files
rm -rf opt/wine
wget https://github.com/mebabo1/menano/releases/download/Box/wine9_9.tar.xz
tar xf wine9_9.tar.xz
rm -rf wine9_9.tar.xz
cd
rm -rf wine9_9.tar.xz
