name: Build Glibc

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      inputGlibcVer:
        description: "Glibc"
        required: true
        default: "glibc-2.41"
  
jobs:
  ubuntu:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Update System Software
        run: |
          sudo apt update
          sudo apt install build-essential
      - name: Download Source Code and Build
        run: |
          glibc_version=${{ github.event.inputs.inputGlibcVer }}
          echo "下载的版本为 $glibc_version"
          if ! wget "https://ftp.gnu.org/gnu/glibc/${glibc_version}.tar.xz"; then
            echo "文件下载失败"
            exit 1
          fi
          mkdir -p /tmp/src
          tar xf *.tar.xz -C /tmp/src
          mkdir -p /tmp/build-glibc/
          cd /tmp/src/*/
          mkdir build
          cd build
          ../configure \
           --prefix=/data/data/com.termux/files/usr/glibc \
           --disable-werror \
           --enable-kernel=4.14

          make -j$(nproc)
          make install DESTDIR=/tmp/pkg
          cd /tmp/pkg
          tar \
           --hard-dereference \
           --numeric-owner \
           --no-same-owner \
           -I "xz -T$(nproc)" \
           -cf /usr/${glibc_version}.tar.xz \
           data/data/com.termux/files/usr/
      
      - name: package and release
        uses:  softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.inputGlibcVer }}
          draft: false
          prerelease: false
          tag_name: ${{ github.event.inputs.inputGlibcVer }}
          body: Build Glibc ${{ github.event.inputs.inputGlibcVer }}
          files: |
            /tmp/${{ github.event.inputs.inputGlibcVer }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



        
