name: Build lsfg-vk ARM64 (Manual)

on:
  workflow_dispatch: # Actions 탭에서 수동으로 버튼을 눌러 실행할 수 있게 합니다.

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout lsfg-vk repository
      uses: actions/checkout@v4
      with:
        repository: PancakeTAS/lsfg-vk  # <== [핵심] 가져올 원본 소스코드 저장소를 정확히 지정합니다.
        fetch-depth: 0
        ref: ff1a0f72a7d6d08b84d58b7b4dc5f05c9f904f98

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git curl llvm clang clang-tools clang-tidy \
          cmake ninja-build pkg-config \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
          libvulkan-dev mesa-common-dev

    - name: Update Vulkan headers
      run: |
        git clone -b vulkan-sdk-1.4.328 https://github.com/KhronosGroup/Vulkan-Headers /tmp/vkh
        sudo rm -rf /usr/include/{vulkan,vk_video}
        sudo mv /tmp/vkh/include/{vulkan,vk_video} /usr/include/
        rm -rf /tmp/vkh

    - name: Configure lsfg-vk
      run: |
        export CFLAGS="-O2"
        export CXXFLAGS="-O2"
        
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_INSTALL_PREFIX=./target \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -DLSFGVK_BUILD_VK_LAYER=ON \
          -DLSFGVK_BUILD_UI=OFF \
          -DLSFGVK_BUILD_CLI=OFF \
          -DLSFGVK_INSTALL_XDG_FILES=OFF \
          -DLSFGVK_LAYER_LIBRARY_PATH="/data/data/com.termux/files/usr/glibc/lib/liblsfg-vk-layer.so"

    - name: Build with Ninja
      run: |
        ninja -C build

    - name: Install with CMake
      run: |
        cmake --install build

    - name: Upload lsfg-vk artifact
      uses: actions/upload-artifact@v4
      with:
        name: lsfg-vk-arm64
        path: target/*
