name: RetroArch Windows ARM64 Build

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  msvc:
    runs-on: windows-2022
    strategy:
      matrix:
        version: [2022]
        configuration: [Release]
        platform: [ARM64]

    steps:
      # RetroArch 공식 저장소 및 서브모듈 직접 체크아웃
      - uses: actions/checkout@v4
        with:
          repository: libretro/RetroArch
          submodules: recursive
          fetch-depth: 0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Compile RA
        working-directory: "${{ github.workspace }}/pkg/msvc"
        run: |
          msbuild -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} .\RetroArch-msvc${{ matrix.version }}.sln

      - name: Get short SHA
        id: slug
        shell: powershell
        run: echo "sha8=$('${{ github.sha }}'.Substring(0,8))" >> $env:GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: retroarch-${{ matrix.platform }}-${{ matrix.configuration }}-${{ steps.slug.outputs.sha8 }}
          path: |
            pkg/msvc/${{ matrix.platform }}/${{ matrix.configuration }}/RetroArch-msvc${{ matrix.version }}.exe
