name: Build lsfg-vk ARM64 (Termux Bionic Native)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout lsfg-vk repository
      uses: actions/checkout@v4
      with:
        repository: xXJSONDeruloXx/lsfg-vk-android
        fetch-depth: 0
        submodules: recursive

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build wget unzip

    - name: Install Android NDK (r27)
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27-linux.zip
        unzip -q android-ndk-r27-linux.zip
        echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r27" >> $GITHUB_ENV

    - name: Android Turnip patches
      run: |
        curl -L https://raw.githubusercontent.com/mebabo1/menano/refs/heads/main/path/image.cpp -o framegen/src/core/image.cpp
  
    - name: Configure lsfg-vk for Termux Bionic
      run: |
        cmake -S lsfg-vk-android -B build -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-26 \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_STANDARD=20 \
          -DCMAKE_CXX_STANDARD_REQUIRED=ON \
          -DCMAKE_INSTALL_PREFIX=./target \
          -DLSFGVK_BUILD_VK_LAYER=ON \
          -DLSFGVK_BUILD_UI=OFF \
          -DLSFGVK_BUILD_CLI=OFF \
          -DLSFGVK_INSTALL_XDG_FILES=OFF \
          -DLSFGVK_LAYER_LIBRARY_PATH="/data/data/com.termux/files/usr/lib/liblsfg-vk-layer.so" \
          -DCMAKE_CXX_FLAGS="-DVK_USE_PLATFORM_ANDROID_KHR -DVK_NO_PROTOTYPES" \
          -DCMAKE_SHARED_LINKER_FLAGS="-llog -Wl,--allow-shlib-undefined -Wl,-rpath,/data/data/com.termux/files/usr/lib" \
          -DCMAKE_EXE_LINKER_FLAGS="-llog -Wl,--allow-shlib-undefined -Wl,-rpath,/data/data/com.termux/files/usr/lib"

    - name: Build
      run: cmake --build build --parallel $(nproc)

    - name: Install
      run: cmake --install build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lsfg-vk-termux-bionic
        path: target/*
