name: Wine arm64ec for Termux

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Wine repository
        uses: actions/checkout@v4

      - name: Install the required deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install -y \
          build-essential \
          lzma \
          flex \
          bison \
          quilt \
          unzip \
          pkg-config \
          libx11-dev:i386 \
          libvulkan-dev:i386 \
          libfreetype6-dev:i386 \
          libxcursor-dev:i386 \
          libxi-dev:i386 \
          libxshmfence-dev:i386 \
          libxxf86vm-dev:i386 \
          libxrandr-dev:i386 \
          libxinerama-dev:i386 \
          libxcomposite-dev:i386 \
          libglu1-mesa-dev:i386 \
          libosmesa6-dev:i386 \
          libdbus-1-dev:i386 \
          libncurses5-dev:i386 \
          libsane-dev:i386 \
          libv4l-dev:i386 \
          libgphoto2-dev:i386 \
          liblcms2-dev:i386 \
          libcapi20-dev:i386 \
          libcups2-dev:i386 \
          libfontconfig1-dev:i386 \
          libgsm1-dev:i386 \
          libtiff5-dev:i386 \
          libmpg123-dev:i386 \
          libopenal-dev:i386 \
          libldap2-dev:i386 \
          libjpeg-dev:i386 \
          libdrm2:i386 \
          libdrm-dev:i386
          sudo apt-get purge -y llvm-18 clang-18
      - name: Downloading and preparing Termux deps
        run: |
          mkdir imagefs
          cd imagefs
          pwd
          wget https://github.com/ziad9267/termux-on-gha/releases/download/test/termuxfs.tar
          tar xf termuxfs.tar
          rm -rf termuxfs.tar
          sudo mv ./data /
          cd /data
          sudo chown -R $(whoami):$(whoami) .
      - name: Download Bylaws toolchain and extracting it
        run: |
          wget https://github.com/bylaws/llvm-mingw/releases/download/20250920/llvm-mingw-20250920-ucrt-ubuntu-22.04-x86_64.tar.xz
          tar -xf llvm-mingw-20250920-ucrt-ubuntu-22.04-x86_64.tar.xz
          rm llvm-mingw-20250920-ucrt-ubuntu-22.04-x86_64.tar.xz
          sudo mv llvm-mingw-20250920-ucrt-ubuntu-22.04-x86_64 /opt/llvm-mingw
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: ndk
        with:
         ndk-version: r28c
         add-to-path: false
         link-to-sdk: true
      - name: Building Wine tools
        run: |
          ./autogen.sh
          mkdir wine-tools
          mkdir wine-tools-build
          cd wine-tools-build
          ../configure --without-x --without-gstreamer --without-vulkan --without-wayland
          make -j$(nproc) __tooldeps__ nls/all
          ls
          mv ./* ../wine-tools
      - name: Compiling Wine
        run: |
          export TOOLCHAIN="/usr/local/lib/android/sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export LLVM_MINGW_TOOLCHAIN="/opt/llvm-mingw/bin"
          export PATH="$LLVM_MINGW_TOOLCHAIN:$PATH"
          export deps="/data/data/com.termux/files/usr"
          export CC="$TOOLCHAIN/clang --target=aarch64-linux-android28"
          export AS=$CC
          export CXX="$TOOLCHAIN/clang++ --target=aarch64-linux-android28"
          export PKG_CONFIG_LIBDIR=$deps/lib/pkgconfig:$deps/share/pkgconfig
          export CPPFLAGS="-I$deps/include"
          export CFLAGS="-I$deps/include -Wno-declaration-after-statement -Wno-implicit-function-declaration -Wno-int-conversion"
          export CXXFLAGS="-Os -s"
          export LDFLAGS="-L$deps/lib"
          export LIBRARY_PATH="$deps/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
          export FREETYPE_CFLAGS="-I$deps/include/freetype2"
          export PULSE_CFLAGS="-I$deps/include/pulse"
          export PULSE_LIBS="-L$deps/lib/pulseaudio -lpulse"
          export SDL2_CFLAGS="-I$deps/include/SDL2"
          export SDL2_LIBS="-L$deps/lib -lSDL2"
          export GSTREAMER_CFLAGS="-I$deps/include/gstreamer-1.0 -I$deps/include/glib-2.0 -I$deps/lib/glib-2.0/include -I$deps/glib-2.0/include -I$deps/lib/gstreamer-1.0/include"
          export GSTREAMER_LIBS="-L$deps/lib -lgstgl-1.0 -lgstapp-1.0 -lgstvideo-1.0 -lgstaudio-1.0 -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lgsttag-1.0 -lgstbase-1.0 -lgstreamer-1.0"
          export FFMPEG_CFLAGS="-I$deps/include/libavutil -I$deps/include/libavcodec -I$deps/include/libavformat"
          export FFMPEG_LIBS="-L$deps/lib -lavutil -lavcodec -lavformat"

          mkdir compiled-files

          ./configure \
          --enable-archs=arm64ec,aarch64,i386 \
          --prefix=/usr \
          --host=aarch64-linux-android \
          --with-mingw=clang \
          --with-wine-tools=./wine-tools \
          --enable-win64 \
          --enable-nls \
          --with-pulse \
          --with-freetype \
          --with-fontconfig \
          --with-gettext \
          --with-sdl \
          --disable-win16 \
          --disable-opencl \
          --without-alsa \
          --disable-tests \
          --without-capi \
          --without-coreaudio \
          --without-cups \
          --without-dbus \
          --without-gphoto \
          --without-gssapi \
          --without-krb5 \
          --without-alsa \
          --without-netapi \
          --without-oss \
          --without-pcap \
          --without-pcsclite \
          --without-sane \
          --without-udev \
          --without-unwind \
          --without-usb \
          --without-v4l2 \
          --without-wayland \
          --without-xinerama \
          --without-xxf86vm \
          --enable-wineandroid_drv=no
          make -j$(nproc)
          #make install -j$(nproc) DESTDIR=compiled-files
        continue-on-error: true

      - name: Recompiling Wine with -landroid-shmem and -landroid-spawn
        run: |
          export TOOLCHAIN="/usr/local/lib/android/sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export LLVM_MINGW_TOOLCHAIN="/opt/llvm-mingw/bin"
          export PATH="$LLVM_MINGW_TOOLCHAIN:$PATH"
          export deps="/data/data/com.termux/files/usr"
          export CC="$TOOLCHAIN/clang --target=aarch64-linux-android28"
          export AS=$CC
          export CXX="$TOOLCHAIN/clang++ --target=aarch64-linux-android28"
          export PKG_CONFIG_LIBDIR=$deps/lib/pkgconfig:$deps/share/pkgconfig
          export CPPFLAGS="-I$deps/include"
          export CFLAGS="-I$deps/include -Wno-declaration-after-statement -Wno-implicit-function-declaration -Wno-int-conversion"
          export CXXFLAGS="-Os -s"
          export LDFLAGS="-L$deps/lib -landroid-shmem -landroid-spawn"
          export LIBRARY_PATH="$deps/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
          export FREETYPE_CFLAGS="-I$deps/include/freetype2"
          export PULSE_CFLAGS="-I$deps/include/pulse"
          export PULSE_LIBS="-L$deps/lib/pulseaudio -lpulse"
          export SDL2_CFLAGS="-I$deps/include/SDL2"
          export SDL2_LIBS="-L$deps/lib -lSDL2"
          export GSTREAMER_CFLAGS="-I$deps/include/gstreamer-1.0 -I$deps/include/glib-2.0 -I$deps/lib/glib-2.0/include -I$deps/glib-2.0/include -I$deps/lib/gstreamer-1.0/include"
          export GSTREAMER_LIBS="-L$deps/lib -lgstgl-1.0 -lgstapp-1.0 -lgstvideo-1.0 -lgstaudio-1.0 -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lgsttag-1.0 -lgstbase-1.0 -lgstreamer-1.0"
          export FFMPEG_CFLAGS="-I$deps/include/libavutil -I$deps/include/libavcodec -I$deps/include/libavformat"
          export FFMPEG_LIBS="-L$deps/lib -lavutil -lavcodec -lavformat"

          ./configure \
          --enable-archs=arm64ec,aarch64,i386 \
          --prefix=/usr \
          --host=aarch64-linux-android \
          --with-mingw=clang \
          --with-wine-tools=./wine-tools \
          --enable-win64 \
          --enable-nls \
          --with-pulse \
          --with-freetype \
          --with-fontconfig \
          --with-gettext \
          --with-sdl \
          --disable-win16 \
          --disable-opencl \
          --without-alsa \
          --disable-tests \
          --without-capi \
          --without-coreaudio \
          --without-cups \
          --without-dbus \
          --without-gphoto \
          --without-gssapi \
          --without-krb5 \
          --without-alsa \
          --without-netapi \
          --without-oss \
          --without-pcap \
          --without-pcsclite \
          --without-sane \
          --without-udev \
          --without-unwind \
          --without-usb \
          --without-v4l2 \
          --without-wayland \
          --without-xinerama \
          --without-xxf86vm \
          --enable-wineandroid_drv=no
          make -j$(nproc)
          make install -j$(nproc) DESTDIR=compiled-files
      - name: Uploading Wine files
        uses: actions/upload-artifact@v4
        with:
          name: wine-build
          path: compiled-files/

      - name: Uploading Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./config.log          
              tar -xf llvm-mingw-20250920-ucrt-ubuntu-22.04-x86_64.tar.xz
              rm llvm-mingw-20250920-ucrt-ubuntu-22.04-x86_64.tar.xz
              sudo mv llvm-mingw-20250920-ucrt-ubuntu-22.04-x86_64 /opt/llvm-mingw
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: NDK
        with:
         ndk-version: r28c
         add-to-path: false
         link-to-sdk: true
      - name: Building Wine tools
        run: |
          ./autogen.sh
          mkdir wine-tools
          mkdir wine-tools-build
          cd wine-tools-build
          ../configure --without-x --without-gstreamer --without-vulkan --without-wayland
          make -j$(nproc) __tooldeps__ nls/all
          ls
          mv ./* ../wine-tools
      - name: Compiling Wine
        run: |
          export TOOLCHAIN="/usr/local/lib/android/sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export LLVM_MINGW_TOOLCHAIN="/opt/llvm-mingw/bin"
          export PATH="$LLVM_MINGW_TOOLCHAIN:$PATH"
          export deps="/data/data/com.termux/files/usr"
          export CC="$TOOLCHAIN/clang --target=aarch64-linux-android28"
          export AS=$CC
          export CXX="$TOOLCHAIN/clang++ --target=aarch64-linux-android28"
          export PKG_CONFIG_LIBDIR=$deps/lib/pkgconfig:$deps/share/pkgconfig
          export CPPFLAGS="-I$deps/include"
          export CFLAGS="-I$deps/include -Wno-declaration-after-statement -Wno-implicit-function-declaration -Wno-int-conversion"
          export CXXFLAGS="-Os -s"
          export LDFLAGS="-L$deps/lib"
          export LIBRARY_PATH="$deps/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
          export FREETYPE_CFLAGS="-I$deps/include/freetype2"
          export PULSE_CFLAGS="-I$deps/include/pulse"
          export PULSE_LIBS="-L$deps/lib/pulseaudio -lpulse"
          export SDL2_CFLAGS="-I$deps/include/SDL2"
          export SDL2_LIBS="-L$deps/lib -lSDL2"
          export GSTREAMER_CFLAGS="-I$deps/include/gstreamer-1.0 -I$deps/include/glib-2.0 -I$deps/lib/glib-2.0/include -I$deps/glib-2.0/include -I$deps/lib/gstreamer-1.0/include"
          export GSTREAMER_LIBS="-L$deps/lib -lgstgl-1.0 -lgstapp-1.0 -lgstvideo-1.0 -lgstaudio-1.0 -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lgsttag-1.0 -lgstbase-1.0 -lgstreamer-1.0"
          export FFMPEG_CFLAGS="-I$deps/include/libavutil -I$deps/include/libavcodec -I$deps/include/libavformat"
          export FFMPEG_LIBS="-L$deps/lib -lavutil -lavcodec -lavformat"

          mkdir compiled-files

          ./configure \
          --enable-archs=arm64ec,aarch64,i386 \
          --prefix=/usr \
          --host=aarch64-linux-android \
          --with-mingw=clang \
          --with-wine-tools=./wine-tools \
          --with-x \
          --with-alsa \
          --with-pulse \
          --with-freetype \
          --with-fontconfig \
          --with-gettext \
          --with-sdl \
          --with-freetype \
          --with-fontconfig \
          --with-gettext \
          --with-sdl \
          --enable-nls \
          --disable-winemenubuilder \
          --disable-win16 \
          --disable-tests \
          --without-ldap \
          --without-capi \
          --without-oss \
          --without-cups \
          --without-dbus \
          --without-coreaudio \
          --without-gphoto \
          --without-osmesa \
          --without-sane \
          --without-pcap \
          --without-pcsclite \
          --without-udev \
          --without-unwind \
          --without-usb \
          --without-v4l2 \
          --without-wayland"
          make -j$(nproc)
          #make install -j$(nproc) DESTDIR=compiled-files
        continue-on-error: true

      - name: Recompiling Wine with -landroid-shmem and -landroid-spawn
        run: |
          export TOOLCHAIN="/usr/local/lib/android/sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export LLVM_MINGW_TOOLCHAIN="/opt/llvm-mingw/bin"
          export PATH="$LLVM_MINGW_TOOLCHAIN:$PATH"
          export deps="/data/data/com.termux/files/usr"
          export CC="$TOOLCHAIN/clang --target=aarch64-linux-android28"
          export AS=$CC
          export CXX="$TOOLCHAIN/clang++ --target=aarch64-linux-android28"
          export PKG_CONFIG_LIBDIR=$deps/lib/pkgconfig:$deps/share/pkgconfig
          export CPPFLAGS="-I$deps/include"
          export CFLAGS="-I$deps/include -Wno-declaration-after-statement -Wno-implicit-function-declaration -Wno-int-conversion"
          export CXXFLAGS="-Os -s"
          export LDFLAGS="-L$deps/lib -landroid-shmem -landroid-spawn"
          export LIBRARY_PATH="$deps/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
          export FREETYPE_CFLAGS="-I$deps/include/freetype2"
          export PULSE_CFLAGS="-I$deps/include/pulse"
          export PULSE_LIBS="-L$deps/lib/pulseaudio -lpulse"
          export SDL2_CFLAGS="-I$deps/include/SDL2"
          export SDL2_LIBS="-L$deps/lib -lSDL2"
          export GSTREAMER_CFLAGS="-I$deps/include/gstreamer-1.0 -I$deps/include/glib-2.0 -I$deps/lib/glib-2.0/include -I$deps/glib-2.0/include -I$deps/lib/gstreamer-1.0/include"
          export GSTREAMER_LIBS="-L$deps/lib -lgstgl-1.0 -lgstapp-1.0 -lgstvideo-1.0 -lgstaudio-1.0 -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lgsttag-1.0 -lgstbase-1.0 -lgstreamer-1.0"
          export FFMPEG_CFLAGS="-I$deps/include/libavutil -I$deps/include/libavcodec -I$deps/include/libavformat"
          export FFMPEG_LIBS="-L$deps/lib -lavutil -lavcodec -lavformat"

          ./configure \
          --enable-archs=arm64ec,aarch64,i386 \
          --prefix=/usr \
          --host=aarch64-linux-android \
          --with-mingw=clang \
          --with-wine-tools=./wine-tools \
          --with-x \
          --with-alsa \
          --with-pulse \
          --with-freetype \
          --with-fontconfig \
          --with-gettext \
          --with-sdl \
          --enable-nls \
          --disable-winemenubuilder \
          --disable-win16 \
          --disable-tests \
          --without-ldap \
          --without-capi \
          --without-oss \
          --without-cups \
          --without-dbus \
          --without-coreaudio \
          --without-gphoto \
          --without-osmesa \
          --without-sane \
          --without-pcap \
          --without-pcsclite \
          --without-udev \
          --without-unwind \
          --without-usb \
          --without-v4l2 \
          --without-wayland"
          make -j$(nproc)
          make install -j$(nproc) DESTDIR=compiled-files
      - name: Uploading Wine files
        uses: actions/upload-artifact@v4
        with:
          name: wine-build
          path: compiled-files/

      - name: Uploading Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./config.log
